### ISSUE TITLE
I am not able to restrict the search through different fields dynamically

### ISSUE THREAD

**Issue by abhinavgurung** [awesome-reactivesearch/airbeds#1]
Hello, so right now its searching across the name field. There are other fields like summary, space and description. If I pass it as an array it will search across all of them. But If I want to have a check box like if user checks description, it will be only searched across description. How can we acheive that.

**Comment by siddharthlatest** [comment]
@AGURUNG31 you can do something like that with a state setting the fields. In your example, if `description` is checked, then set that as a search field. If not, then set something else.

**Comment by abhinavgurung** [comment]
@siddharthlatest 
Thanks for the reply. So right now my checkboxes are in the MultiDataList component. so does the MultiDataList selection will be known to CategorySearch component. I am new to react itself. when you say "set that as a search field", how is this achieved. Thanks

**Comment by siddharthlatest** [comment]
You can use the onValueChange callback to set the state (an Array, for
e.g.) in your React app, and that state var is used as the value of the
dataField prop in the search component. Hope this helps!

**Comment by abhinavgurung** [comment]
so you are saying, the the selected filters will be passed from the MultiDataList to search component, each time the selected filters of multidatalist component changes.
