### ISSUE TITLE
can we include an express/nodejs server in between reactivesBase component and elasticsearch

### ISSUE THREAD

**Issue by abhinavgurung** [awesome-reactivesearch/airbeds#2]
is there any example how we can keep the UI/client separate and not too tightly connected to elasticsearch and have an express server in between.

components such as multiList gets the UI data directly from the es index. how willl this be tackled?

**Comment by siddharthlatest** [comment]
You can see how to set up a proxy server over here: https://opensource.appbase.io/reactive-manual/getting-started/reactivebase.html#connect-to-elasticsearch.
